name: tesla_fleet_api
description: A Dart package for interacting with Tesla Fleet API
version: 1.0.0
homepage: https://github.com/cutmail/tesla_fleet_api

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  http: ^1.6.0
  crypto: ^3.0.7
  jwt_decode: ^0.3.1
  json_annotation: ^4.9.0

dev_dependencies:
  test: ^1.28.0
  build_runner: ^2.10.5
  json_serializable: ^6.11.2
  lints: ^6.0.0

topics:
  - tesla
  - api
  - fleet
  - automotive